# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger'
gem 'minitest-power_assert'
gem 'puma'
gem 'rack'
gem 'rack-heartbeat'
gem 'rack-minitest'
gem 'rack-unreloader'
gem 'rackup'
gem 'rake'
gem 'rubocop'
gem 'thin'
gem 'webrick'
